[project]
name = "mtg-combo-cube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
